# Generated by Django 5.1.15 on 2026-10-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuegosIndieGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título del Juego')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de Portada')),
                ('subgenre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subgénero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
